baseurl = "/"
defaultContentLanguage = "fi"
languageCode = "fi-FI"
languageLang = "fi"
title = "Oskar Thun"
subtitle = "Nettisivuja jo vuodesta 2014"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]
